/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package uk.co.cathtanconsulting.twitter;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TweetRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TweetRecord\",\"namespace\":\"uk.co.cathtanconsulting.twitter\",\"fields\":[{\"name\":\"created_at_str\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"unknown\"},{\"name\":\"created_at_long\",\"type\":\"long\"},{\"name\":\"tweet\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"The content of the user's Twitter message\"},{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"in_reply_to_status_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"in_reply_to_user_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"user_id\",\"type\":\"long\"},{\"name\":\"user_screen_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"user_location\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"user_followers_count\",\"type\":\"int\"},{\"name\":\"user_friends_count\",\"type\":\"int\"},{\"name\":\"retweeted_status_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"retweeted_user_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"geo_lat\",\"type\":[\"null\",\"double\"]},{\"name\":\"geo_long\",\"type\":[\"null\",\"double\"]},{\"name\":\"geo_type\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Will either be Point or null\"}],\"doc:\":\"A basic schema for storing Twitter messages\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String created_at_str;
  @Deprecated public long created_at_long;
  /** The content of the user's Twitter message */
  @Deprecated public java.lang.String tweet;
  @Deprecated public long id;
  @Deprecated public java.lang.Long in_reply_to_status_id;
  @Deprecated public java.lang.Long in_reply_to_user_id;
  @Deprecated public long user_id;
  @Deprecated public java.lang.String user_screen_name;
  @Deprecated public java.lang.String user_location;
  @Deprecated public int user_followers_count;
  @Deprecated public int user_friends_count;
  @Deprecated public java.lang.Long retweeted_status_id;
  @Deprecated public java.lang.Long retweeted_user_id;
  @Deprecated public java.lang.Double geo_lat;
  @Deprecated public java.lang.Double geo_long;
  /** Will either be Point or null */
  @Deprecated public java.lang.String geo_type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public TweetRecord() {}

  /**
   * All-args constructor.
   */
  public TweetRecord(java.lang.String created_at_str, java.lang.Long created_at_long, java.lang.String tweet, java.lang.Long id, java.lang.Long in_reply_to_status_id, java.lang.Long in_reply_to_user_id, java.lang.Long user_id, java.lang.String user_screen_name, java.lang.String user_location, java.lang.Integer user_followers_count, java.lang.Integer user_friends_count, java.lang.Long retweeted_status_id, java.lang.Long retweeted_user_id, java.lang.Double geo_lat, java.lang.Double geo_long, java.lang.String geo_type) {
    this.created_at_str = created_at_str;
    this.created_at_long = created_at_long;
    this.tweet = tweet;
    this.id = id;
    this.in_reply_to_status_id = in_reply_to_status_id;
    this.in_reply_to_user_id = in_reply_to_user_id;
    this.user_id = user_id;
    this.user_screen_name = user_screen_name;
    this.user_location = user_location;
    this.user_followers_count = user_followers_count;
    this.user_friends_count = user_friends_count;
    this.retweeted_status_id = retweeted_status_id;
    this.retweeted_user_id = retweeted_user_id;
    this.geo_lat = geo_lat;
    this.geo_long = geo_long;
    this.geo_type = geo_type;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return created_at_str;
    case 1: return created_at_long;
    case 2: return tweet;
    case 3: return id;
    case 4: return in_reply_to_status_id;
    case 5: return in_reply_to_user_id;
    case 6: return user_id;
    case 7: return user_screen_name;
    case 8: return user_location;
    case 9: return user_followers_count;
    case 10: return user_friends_count;
    case 11: return retweeted_status_id;
    case 12: return retweeted_user_id;
    case 13: return geo_lat;
    case 14: return geo_long;
    case 15: return geo_type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: created_at_str = (java.lang.String)value$; break;
    case 1: created_at_long = (java.lang.Long)value$; break;
    case 2: tweet = (java.lang.String)value$; break;
    case 3: id = (java.lang.Long)value$; break;
    case 4: in_reply_to_status_id = (java.lang.Long)value$; break;
    case 5: in_reply_to_user_id = (java.lang.Long)value$; break;
    case 6: user_id = (java.lang.Long)value$; break;
    case 7: user_screen_name = (java.lang.String)value$; break;
    case 8: user_location = (java.lang.String)value$; break;
    case 9: user_followers_count = (java.lang.Integer)value$; break;
    case 10: user_friends_count = (java.lang.Integer)value$; break;
    case 11: retweeted_status_id = (java.lang.Long)value$; break;
    case 12: retweeted_user_id = (java.lang.Long)value$; break;
    case 13: geo_lat = (java.lang.Double)value$; break;
    case 14: geo_long = (java.lang.Double)value$; break;
    case 15: geo_type = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'created_at_str' field.
   */
  public java.lang.String getCreatedAtStr() {
    return created_at_str;
  }

  /**
   * Sets the value of the 'created_at_str' field.
   * @param value the value to set.
   */
  public void setCreatedAtStr(java.lang.String value) {
    this.created_at_str = value;
  }

  /**
   * Gets the value of the 'created_at_long' field.
   */
  public java.lang.Long getCreatedAtLong() {
    return created_at_long;
  }

  /**
   * Sets the value of the 'created_at_long' field.
   * @param value the value to set.
   */
  public void setCreatedAtLong(java.lang.Long value) {
    this.created_at_long = value;
  }

  /**
   * Gets the value of the 'tweet' field.
   * The content of the user's Twitter message   */
  public java.lang.String getTweet() {
    return tweet;
  }

  /**
   * Sets the value of the 'tweet' field.
   * The content of the user's Twitter message   * @param value the value to set.
   */
  public void setTweet(java.lang.String value) {
    this.tweet = value;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'in_reply_to_status_id' field.
   */
  public java.lang.Long getInReplyToStatusId() {
    return in_reply_to_status_id;
  }

  /**
   * Sets the value of the 'in_reply_to_status_id' field.
   * @param value the value to set.
   */
  public void setInReplyToStatusId(java.lang.Long value) {
    this.in_reply_to_status_id = value;
  }

  /**
   * Gets the value of the 'in_reply_to_user_id' field.
   */
  public java.lang.Long getInReplyToUserId() {
    return in_reply_to_user_id;
  }

  /**
   * Sets the value of the 'in_reply_to_user_id' field.
   * @param value the value to set.
   */
  public void setInReplyToUserId(java.lang.Long value) {
    this.in_reply_to_user_id = value;
  }

  /**
   * Gets the value of the 'user_id' field.
   */
  public java.lang.Long getUserId() {
    return user_id;
  }

  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.Long value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'user_screen_name' field.
   */
  public java.lang.String getUserScreenName() {
    return user_screen_name;
  }

  /**
   * Sets the value of the 'user_screen_name' field.
   * @param value the value to set.
   */
  public void setUserScreenName(java.lang.String value) {
    this.user_screen_name = value;
  }

  /**
   * Gets the value of the 'user_location' field.
   */
  public java.lang.String getUserLocation() {
    return user_location;
  }

  /**
   * Sets the value of the 'user_location' field.
   * @param value the value to set.
   */
  public void setUserLocation(java.lang.String value) {
    this.user_location = value;
  }

  /**
   * Gets the value of the 'user_followers_count' field.
   */
  public java.lang.Integer getUserFollowersCount() {
    return user_followers_count;
  }

  /**
   * Sets the value of the 'user_followers_count' field.
   * @param value the value to set.
   */
  public void setUserFollowersCount(java.lang.Integer value) {
    this.user_followers_count = value;
  }

  /**
   * Gets the value of the 'user_friends_count' field.
   */
  public java.lang.Integer getUserFriendsCount() {
    return user_friends_count;
  }

  /**
   * Sets the value of the 'user_friends_count' field.
   * @param value the value to set.
   */
  public void setUserFriendsCount(java.lang.Integer value) {
    this.user_friends_count = value;
  }

  /**
   * Gets the value of the 'retweeted_status_id' field.
   */
  public java.lang.Long getRetweetedStatusId() {
    return retweeted_status_id;
  }

  /**
   * Sets the value of the 'retweeted_status_id' field.
   * @param value the value to set.
   */
  public void setRetweetedStatusId(java.lang.Long value) {
    this.retweeted_status_id = value;
  }

  /**
   * Gets the value of the 'retweeted_user_id' field.
   */
  public java.lang.Long getRetweetedUserId() {
    return retweeted_user_id;
  }

  /**
   * Sets the value of the 'retweeted_user_id' field.
   * @param value the value to set.
   */
  public void setRetweetedUserId(java.lang.Long value) {
    this.retweeted_user_id = value;
  }

  /**
   * Gets the value of the 'geo_lat' field.
   */
  public java.lang.Double getGeoLat() {
    return geo_lat;
  }

  /**
   * Sets the value of the 'geo_lat' field.
   * @param value the value to set.
   */
  public void setGeoLat(java.lang.Double value) {
    this.geo_lat = value;
  }

  /**
   * Gets the value of the 'geo_long' field.
   */
  public java.lang.Double getGeoLong() {
    return geo_long;
  }

  /**
   * Sets the value of the 'geo_long' field.
   * @param value the value to set.
   */
  public void setGeoLong(java.lang.Double value) {
    this.geo_long = value;
  }

  /**
   * Gets the value of the 'geo_type' field.
   * Will either be Point or null   */
  public java.lang.String getGeoType() {
    return geo_type;
  }

  /**
   * Sets the value of the 'geo_type' field.
   * Will either be Point or null   * @param value the value to set.
   */
  public void setGeoType(java.lang.String value) {
    this.geo_type = value;
  }

  /** Creates a new TweetRecord RecordBuilder */
  public static uk.co.cathtanconsulting.twitter.TweetRecord.Builder newBuilder() {
    return new uk.co.cathtanconsulting.twitter.TweetRecord.Builder();
  }
  
  /** Creates a new TweetRecord RecordBuilder by copying an existing Builder */
  public static uk.co.cathtanconsulting.twitter.TweetRecord.Builder newBuilder(uk.co.cathtanconsulting.twitter.TweetRecord.Builder other) {
    return new uk.co.cathtanconsulting.twitter.TweetRecord.Builder(other);
  }
  
  /** Creates a new TweetRecord RecordBuilder by copying an existing TweetRecord instance */
  public static uk.co.cathtanconsulting.twitter.TweetRecord.Builder newBuilder(uk.co.cathtanconsulting.twitter.TweetRecord other) {
    return new uk.co.cathtanconsulting.twitter.TweetRecord.Builder(other);
  }
  
  /**
   * RecordBuilder for TweetRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TweetRecord>
    implements org.apache.avro.data.RecordBuilder<TweetRecord> {

    private java.lang.String created_at_str;
    private long created_at_long;
    private java.lang.String tweet;
    private long id;
    private java.lang.Long in_reply_to_status_id;
    private java.lang.Long in_reply_to_user_id;
    private long user_id;
    private java.lang.String user_screen_name;
    private java.lang.String user_location;
    private int user_followers_count;
    private int user_friends_count;
    private java.lang.Long retweeted_status_id;
    private java.lang.Long retweeted_user_id;
    private java.lang.Double geo_lat;
    private java.lang.Double geo_long;
    private java.lang.String geo_type;

    /** Creates a new Builder */
    private Builder() {
      super(uk.co.cathtanconsulting.twitter.TweetRecord.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(uk.co.cathtanconsulting.twitter.TweetRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.created_at_str)) {
        this.created_at_str = data().deepCopy(fields()[0].schema(), other.created_at_str);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.created_at_long)) {
        this.created_at_long = data().deepCopy(fields()[1].schema(), other.created_at_long);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tweet)) {
        this.tweet = data().deepCopy(fields()[2].schema(), other.tweet);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.id)) {
        this.id = data().deepCopy(fields()[3].schema(), other.id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.in_reply_to_status_id)) {
        this.in_reply_to_status_id = data().deepCopy(fields()[4].schema(), other.in_reply_to_status_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.in_reply_to_user_id)) {
        this.in_reply_to_user_id = data().deepCopy(fields()[5].schema(), other.in_reply_to_user_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.user_id)) {
        this.user_id = data().deepCopy(fields()[6].schema(), other.user_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.user_screen_name)) {
        this.user_screen_name = data().deepCopy(fields()[7].schema(), other.user_screen_name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.user_location)) {
        this.user_location = data().deepCopy(fields()[8].schema(), other.user_location);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.user_followers_count)) {
        this.user_followers_count = data().deepCopy(fields()[9].schema(), other.user_followers_count);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.user_friends_count)) {
        this.user_friends_count = data().deepCopy(fields()[10].schema(), other.user_friends_count);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.retweeted_status_id)) {
        this.retweeted_status_id = data().deepCopy(fields()[11].schema(), other.retweeted_status_id);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.retweeted_user_id)) {
        this.retweeted_user_id = data().deepCopy(fields()[12].schema(), other.retweeted_user_id);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.geo_lat)) {
        this.geo_lat = data().deepCopy(fields()[13].schema(), other.geo_lat);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.geo_long)) {
        this.geo_long = data().deepCopy(fields()[14].schema(), other.geo_long);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.geo_type)) {
        this.geo_type = data().deepCopy(fields()[15].schema(), other.geo_type);
        fieldSetFlags()[15] = true;
      }
    }
    
    /** Creates a Builder by copying an existing TweetRecord instance */
    private Builder(uk.co.cathtanconsulting.twitter.TweetRecord other) {
            super(uk.co.cathtanconsulting.twitter.TweetRecord.SCHEMA$);
      if (isValidValue(fields()[0], other.created_at_str)) {
        this.created_at_str = data().deepCopy(fields()[0].schema(), other.created_at_str);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.created_at_long)) {
        this.created_at_long = data().deepCopy(fields()[1].schema(), other.created_at_long);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tweet)) {
        this.tweet = data().deepCopy(fields()[2].schema(), other.tweet);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.id)) {
        this.id = data().deepCopy(fields()[3].schema(), other.id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.in_reply_to_status_id)) {
        this.in_reply_to_status_id = data().deepCopy(fields()[4].schema(), other.in_reply_to_status_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.in_reply_to_user_id)) {
        this.in_reply_to_user_id = data().deepCopy(fields()[5].schema(), other.in_reply_to_user_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.user_id)) {
        this.user_id = data().deepCopy(fields()[6].schema(), other.user_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.user_screen_name)) {
        this.user_screen_name = data().deepCopy(fields()[7].schema(), other.user_screen_name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.user_location)) {
        this.user_location = data().deepCopy(fields()[8].schema(), other.user_location);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.user_followers_count)) {
        this.user_followers_count = data().deepCopy(fields()[9].schema(), other.user_followers_count);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.user_friends_count)) {
        this.user_friends_count = data().deepCopy(fields()[10].schema(), other.user_friends_count);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.retweeted_status_id)) {
        this.retweeted_status_id = data().deepCopy(fields()[11].schema(), other.retweeted_status_id);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.retweeted_user_id)) {
        this.retweeted_user_id = data().deepCopy(fields()[12].schema(), other.retweeted_user_id);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.geo_lat)) {
        this.geo_lat = data().deepCopy(fields()[13].schema(), other.geo_lat);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.geo_long)) {
        this.geo_long = data().deepCopy(fields()[14].schema(), other.geo_long);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.geo_type)) {
        this.geo_type = data().deepCopy(fields()[15].schema(), other.geo_type);
        fieldSetFlags()[15] = true;
      }
    }

    /** Gets the value of the 'created_at_str' field */
    public java.lang.String getCreatedAtStr() {
      return created_at_str;
    }
    
    /** Sets the value of the 'created_at_str' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setCreatedAtStr(java.lang.String value) {
      validate(fields()[0], value);
      this.created_at_str = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'created_at_str' field has been set */
    public boolean hasCreatedAtStr() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'created_at_str' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearCreatedAtStr() {
      created_at_str = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'created_at_long' field */
    public java.lang.Long getCreatedAtLong() {
      return created_at_long;
    }
    
    /** Sets the value of the 'created_at_long' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setCreatedAtLong(long value) {
      validate(fields()[1], value);
      this.created_at_long = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'created_at_long' field has been set */
    public boolean hasCreatedAtLong() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'created_at_long' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearCreatedAtLong() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'tweet' field */
    public java.lang.String getTweet() {
      return tweet;
    }
    
    /** Sets the value of the 'tweet' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setTweet(java.lang.String value) {
      validate(fields()[2], value);
      this.tweet = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'tweet' field has been set */
    public boolean hasTweet() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'tweet' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearTweet() {
      tweet = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'id' field */
    public java.lang.Long getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setId(long value) {
      validate(fields()[3], value);
      this.id = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'id' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearId() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'in_reply_to_status_id' field */
    public java.lang.Long getInReplyToStatusId() {
      return in_reply_to_status_id;
    }
    
    /** Sets the value of the 'in_reply_to_status_id' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setInReplyToStatusId(java.lang.Long value) {
      validate(fields()[4], value);
      this.in_reply_to_status_id = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'in_reply_to_status_id' field has been set */
    public boolean hasInReplyToStatusId() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'in_reply_to_status_id' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearInReplyToStatusId() {
      in_reply_to_status_id = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'in_reply_to_user_id' field */
    public java.lang.Long getInReplyToUserId() {
      return in_reply_to_user_id;
    }
    
    /** Sets the value of the 'in_reply_to_user_id' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setInReplyToUserId(java.lang.Long value) {
      validate(fields()[5], value);
      this.in_reply_to_user_id = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'in_reply_to_user_id' field has been set */
    public boolean hasInReplyToUserId() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'in_reply_to_user_id' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearInReplyToUserId() {
      in_reply_to_user_id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'user_id' field */
    public java.lang.Long getUserId() {
      return user_id;
    }
    
    /** Sets the value of the 'user_id' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setUserId(long value) {
      validate(fields()[6], value);
      this.user_id = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'user_id' field has been set */
    public boolean hasUserId() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'user_id' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearUserId() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'user_screen_name' field */
    public java.lang.String getUserScreenName() {
      return user_screen_name;
    }
    
    /** Sets the value of the 'user_screen_name' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setUserScreenName(java.lang.String value) {
      validate(fields()[7], value);
      this.user_screen_name = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'user_screen_name' field has been set */
    public boolean hasUserScreenName() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'user_screen_name' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearUserScreenName() {
      user_screen_name = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'user_location' field */
    public java.lang.String getUserLocation() {
      return user_location;
    }
    
    /** Sets the value of the 'user_location' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setUserLocation(java.lang.String value) {
      validate(fields()[8], value);
      this.user_location = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'user_location' field has been set */
    public boolean hasUserLocation() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'user_location' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearUserLocation() {
      user_location = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'user_followers_count' field */
    public java.lang.Integer getUserFollowersCount() {
      return user_followers_count;
    }
    
    /** Sets the value of the 'user_followers_count' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setUserFollowersCount(int value) {
      validate(fields()[9], value);
      this.user_followers_count = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'user_followers_count' field has been set */
    public boolean hasUserFollowersCount() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'user_followers_count' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearUserFollowersCount() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'user_friends_count' field */
    public java.lang.Integer getUserFriendsCount() {
      return user_friends_count;
    }
    
    /** Sets the value of the 'user_friends_count' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setUserFriendsCount(int value) {
      validate(fields()[10], value);
      this.user_friends_count = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'user_friends_count' field has been set */
    public boolean hasUserFriendsCount() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'user_friends_count' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearUserFriendsCount() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'retweeted_status_id' field */
    public java.lang.Long getRetweetedStatusId() {
      return retweeted_status_id;
    }
    
    /** Sets the value of the 'retweeted_status_id' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setRetweetedStatusId(java.lang.Long value) {
      validate(fields()[11], value);
      this.retweeted_status_id = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'retweeted_status_id' field has been set */
    public boolean hasRetweetedStatusId() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'retweeted_status_id' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearRetweetedStatusId() {
      retweeted_status_id = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'retweeted_user_id' field */
    public java.lang.Long getRetweetedUserId() {
      return retweeted_user_id;
    }
    
    /** Sets the value of the 'retweeted_user_id' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setRetweetedUserId(java.lang.Long value) {
      validate(fields()[12], value);
      this.retweeted_user_id = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'retweeted_user_id' field has been set */
    public boolean hasRetweetedUserId() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'retweeted_user_id' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearRetweetedUserId() {
      retweeted_user_id = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'geo_lat' field */
    public java.lang.Double getGeoLat() {
      return geo_lat;
    }
    
    /** Sets the value of the 'geo_lat' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setGeoLat(java.lang.Double value) {
      validate(fields()[13], value);
      this.geo_lat = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'geo_lat' field has been set */
    public boolean hasGeoLat() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'geo_lat' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearGeoLat() {
      geo_lat = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'geo_long' field */
    public java.lang.Double getGeoLong() {
      return geo_long;
    }
    
    /** Sets the value of the 'geo_long' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setGeoLong(java.lang.Double value) {
      validate(fields()[14], value);
      this.geo_long = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'geo_long' field has been set */
    public boolean hasGeoLong() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'geo_long' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearGeoLong() {
      geo_long = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'geo_type' field */
    public java.lang.String getGeoType() {
      return geo_type;
    }
    
    /** Sets the value of the 'geo_type' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder setGeoType(java.lang.String value) {
      validate(fields()[15], value);
      this.geo_type = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'geo_type' field has been set */
    public boolean hasGeoType() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'geo_type' field */
    public uk.co.cathtanconsulting.twitter.TweetRecord.Builder clearGeoType() {
      geo_type = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    @Override
    public TweetRecord build() {
      try {
        TweetRecord record = new TweetRecord();
        record.created_at_str = fieldSetFlags()[0] ? this.created_at_str : (java.lang.String) defaultValue(fields()[0]);
        record.created_at_long = fieldSetFlags()[1] ? this.created_at_long : (java.lang.Long) defaultValue(fields()[1]);
        record.tweet = fieldSetFlags()[2] ? this.tweet : (java.lang.String) defaultValue(fields()[2]);
        record.id = fieldSetFlags()[3] ? this.id : (java.lang.Long) defaultValue(fields()[3]);
        record.in_reply_to_status_id = fieldSetFlags()[4] ? this.in_reply_to_status_id : (java.lang.Long) defaultValue(fields()[4]);
        record.in_reply_to_user_id = fieldSetFlags()[5] ? this.in_reply_to_user_id : (java.lang.Long) defaultValue(fields()[5]);
        record.user_id = fieldSetFlags()[6] ? this.user_id : (java.lang.Long) defaultValue(fields()[6]);
        record.user_screen_name = fieldSetFlags()[7] ? this.user_screen_name : (java.lang.String) defaultValue(fields()[7]);
        record.user_location = fieldSetFlags()[8] ? this.user_location : (java.lang.String) defaultValue(fields()[8]);
        record.user_followers_count = fieldSetFlags()[9] ? this.user_followers_count : (java.lang.Integer) defaultValue(fields()[9]);
        record.user_friends_count = fieldSetFlags()[10] ? this.user_friends_count : (java.lang.Integer) defaultValue(fields()[10]);
        record.retweeted_status_id = fieldSetFlags()[11] ? this.retweeted_status_id : (java.lang.Long) defaultValue(fields()[11]);
        record.retweeted_user_id = fieldSetFlags()[12] ? this.retweeted_user_id : (java.lang.Long) defaultValue(fields()[12]);
        record.geo_lat = fieldSetFlags()[13] ? this.geo_lat : (java.lang.Double) defaultValue(fields()[13]);
        record.geo_long = fieldSetFlags()[14] ? this.geo_long : (java.lang.Double) defaultValue(fields()[14]);
        record.geo_type = fieldSetFlags()[15] ? this.geo_type : (java.lang.String) defaultValue(fields()[15]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
